### ISSUE TITLE
Settings page not working properly

### ISSUE THREAD

**Issue by Meghdut-Mandal** [Meghdut-Mandal/GitOnAndroid#4]
**Describe the bug**
Fields, not showing a preview of the changes in them. 

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to the home screen.
2. Click on the settings icon
3. Settings page will open 
3. Tap on User Name
4. Enter a New user name 
5. Tap on okay
6. See the grey text below User Name should be updated with the new one 
7. Simplerly you can tap on the "Set colour theme"
8. See none is Selected, although the change is reflected.

**Expected behaviour**
* The fields should reflect the chanes 
* The settings activity shouldn't restart 

**Screenshots**
![image](https://user-images.githubusercontent.com/39855414/136361710-6cc2b709-6254-4b9c-a72a-708eccc774bc.png)

**Smartphone (please complete the following information):**
 - Device: Poco F1
 - OS: Android 11

**Comment by Dajvytmo** [comment]
Hello, @Meghdut-Mandal can I work on this?

**Comment by Meghdut-Mandal** [comment]
Sure @Dajvytmo
